### ISSUE TITLE
AT-X視聴時に別のサービスと認識されてしまう

### ISSUE THREAD

**Issue by mayoineko33** [SlashNephy/TVTestAnnictRecorder#24]
AT-X視聴時に同一トラポンの別サービスのSKY STAGEと認識されてしまって放送時刻データがありませんとなってしまいます

**Comment by SlashNephy** [comment]
私の環境では再現していません。
問題の切り分けをしたいので、差し支えなければ以下の情報を提供していただけませんか？
- TVTest 右クリック → 設定 → ログのスクリーンショット
- AT-X を選局した状態で TVTest 右クリック → ストリームの情報のスクリーンショット

**Comment by mayoineko33** [comment]
![t1](https://github.com/user-attachments/assets/78b083e6-9581-480e-ae33-2e45ced8beff)
![t2](https://github.com/user-attachments/assets/ddabb025-da48-47da-a580-f9c5f0a97324)

**Comment by SlashNephy** [comment]
提供ありがとうございます！
ストリームに複数のサービスが含まれていると発生する問題のようでした
(私の環境では BonDriver_Mirakurun を使用していて、1サービスのみが流れてくるので再現しなかったようです)

修正してみます

**Comment by SlashNephy** [comment]
こちらで修正してみましたのでご確認いただけますか？
https://github.com/SlashNephy/TVTestAnnictRecorder/releases/tag/1.0.1

**Comment by mayoineko33** [comment]
正常に動作するようになりました
対応ありがとうございます
